### ISSUE TITLE
Add host attribute to the HTTPRequest class and a getter

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#124]
I would need it. I'll check if I'm able to do it by myself though …

**Comment by dantol29** [comment]
@slombard All headers are stored in the \_headers

**Comment by 552020** [comment]
All right, I added a getHost() method in the branch slombard/web-106-add-host-attribute-to-the-httprequest-class-and-a-getter which I will merge now in 36

**Comment by dantol29** [comment]
Wait, it should be host, not Host. I made all of them lowercase

**Comment by 552020** [comment]
What do you mean? Cause I wrote getHost and not gethost? The code I wrote was working …<br><br>Or you mean in the code?

<img src="https://uploads.linear.app/3a13e0cf-cf78-41bb-abe3-8d0765670e8b/7924c4d8-f45e-4a6a-a468-8d5f5024b001/404cad05-d2d2-4249-86f0-e045ebd73824?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNhMTNlMGNmLWNmNzgtNDFiYi1hYmUzLThkMDc2NTY3MGU4Yi83OTI0YzRkOC1mNDVlLTRhNmEtYTQ2OC04ZDVmNTAyNGIwMDEvNDA0Y2FkMDUtZDJkMi00MjQ5LTg2ZjAtZTA0NWViZDczODI0IiwiaWF0IjoxNzEyOTk1MTMxLCJleHAiOjMzMjgzNTU1MTMxfQ.2LgBLr6Lp3i2XO1bSjKzfXZPvSJbY1kodVXqZnEcl8E " alt="image.png" width="607" height="160" />

**Comment by dantol29** [comment]
Since headers are case-insensitive I added the function to make all of them lowercase. That is why you should seach 'host' instead of 'Host'
