### ISSUE TITLE
Implement 'Clients must be able to upload files.'

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#127]
This is a subject requirement we still miss.

And we have also this extra requirement

> *Setup routes with one or multiple of the following rules/configuration (routes wont*
>
> *be using regexp):*
>
> \[…\]
>
> \- *Make the route able to accept uploaded files and configure where they should*
>
> *be saved.*

> 

I researched a little bit the issue. The ability to upload a file, means that our server needs to handle a POST request with 'Content-Type: multipart/form-data;'. In the header we will have also a `boundary=` key, whose value will be the delimiter in the body to signalize the beginning and the end of the file:. It could look like this: `boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW`.

The http request could have a fixed content length or be of type chunked body. This means that the 'core' doesn't have to do any extra work in this case, it's more a parser (@dtolmaco) and a request-handler (@lmangall) thing.

This is how a request for a file upload could looks like:

```
POST /upload HTTP/1.1
Host: example.com
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Length: 234

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

Hello, world!
------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

Breakdown of the request:

* **POST /upload HTTP/1.1**: This line indicates the method (POST), the path to the resource where the data should be sent (`/upload`), and the HTTP version (1.1).
* **Host**: we know.
* **Content-Type**: This indicates that the body of the request uses `multipart/form-data` encoding which is necessary for file upload. The `boundary` parameter idefines the delimiter between different parts of the message body.
* **Content-Length**: We know.
* **Content-Disposition** (within the body): Specifies that the part contains form data. The `name="file"` attribute is typically the name of the input field from the HTML form. The `filename="test.txt"` attribute specifies the filename that will be used by the server to refer to the uploaded file.
* **Content-Type** (within the body): The MIME type of the file being uploaded, in this case, `text/plain` because it's a plain text file.

How to test:

* curl -X POST -F "file=@test.txt" [http://example.com/upload](http://example.com/upload)

**Comment by dantol29** [comment]
I made a branch `git checkout 127-implement-clients-must-be-able-to-upload-files`. I gonna add there everything that is necessary from HTTPRequest class

**Comment by dantol29** [comment]
Done a while ago... Now we have directive `upload_path` for this
