### ISSUE TITLE
Implement ability of listening on multiple ports (through the configuration file)

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#128]
This is a requirement form the subject:

> *Your server must be able to listen to multiple ports (see Configuration file).*

We should be able to listen to localhost:8080 and localhost:8081.

It is not possible to bind a server socket to multiple ports. The only way we have to let a sever listen to multiple ports in a single thread server is to create multiple server sockets.

if we to `bind()` a socket that is already bound, the system will typically return an `EINVAL` error, indicating that the socket is already bound to an address.

A server socket can listen to multiple IP Addresses with INADDR_ANY set on the in_addr struct like this `_serverAddr.sin_addr.s_addr = htonl(INADDR_ANY);`

A server socket can listen to 1 IP Address or to all, but not to two.

This is a possible configuration file for a server listening to multiple ports:

## Server for HTTP traffic on port 80

server {

```
listen 80;

server_name www.example.com;

root /var/www/html;

index index.html index.htm;

location / {

    try_files $uri $uri/ =404;

}
```

}

## Server for HTTPS traffic on port 443

```
server {
listen 443 ssl;

server_name www.example.com;

ssl_certificate /etc/ssl/certs/example.pem;

ssl_certificate_key /etc/ssl/private/example.key;

root /var/www/html;

index index.html index.htm;

location / {

    try_files $uri $uri/ =404;

}
}
```

We could have the case of a website available on port 80 and 8080 and another one on port 80 and port 8081. We will know to which port came the request, figuring out which server socket was hit by the request. In the case above we will have three sockets 1 for port 80, 1 for port 8080 and 1 for port 8081. The Server Socket object should keep trace on which port he's listening to, and pass this information to the router.

I tag @lmangall cause this information will be relevant for the router then. Cause a request coming to port 8081 for [example.com](http://example.com) if the virtual server of [example.c](http://example.com)om is listening only on port 80 and 8080 will be invalid.

**Comment by dantol29** [comment]
@552020 Done?

**Comment by 552020** [comment]
@dantol29 You tell me cause you approved a PR about it. Didn't you? Is it done?
