### ISSUE TITLE
test link between linear sub-issue and github's PR

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#14]
@slombard said in [WEB-16](https://linear.app/web-serv/issue/WEB-16/test-issue-for-leo#comment-8f0cd1d3):

> So the hypothesis is that sub-issues created in linear are not linked to the PR in GitHub? We can test this. Creating a sub-issue to this issue …

**Comment by 552020** [comment]
<img src="https://uploads.linear.app/3a13e0cf-cf78-41bb-abe3-8d0765670e8b/2ff78e57-f488-4a4c-8858-5d65e87c5f4d/aab69baf-701c-4552-a1ef-56fe0a156d32?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNhMTNlMGNmLWNmNzgtNDFiYi1hYmUzLThkMDc2NTY3MGU4Yi8yZmY3OGU1Ny1mNDg4LTRhNGMtODg1OC01ZDY1ZTg3YzVmNGQvYWFiNjliYWYtNzAxYy00NTUyLWExZWYtNTZmZTBhMTU2ZDMyIiwiaWF0IjoxNzExNTcyOTc0LCJleHAiOjMzMjgyMTMyOTc0fQ._kfaCrtMHIpQlCvLk8fZtyjnaZ365j0yGcl6J6keXDM " alt="image.png" width="948" height="201" />

It seems it's working fine (on my machine …)

Did you link your github with linear? @lmangall

**Comment by lmangall** [comment]
I did, I think it's all good, I was just mentioning a way to link between GitHub and Linear, that if you post a link on GitHub Linear tags it as linked on its side
