### ISSUE TITLE
Start working on CGI

### ISSUE THREAD

**Issue by lmangall** [dantol29/webserver#18]
Exploring the CGI

**Comment by lmangall** [comment]
First version available:
- there is a program in C++ that gets compiled into hello.cgi.
- the "core" should be abloe to execute it
- through its standard output (cout <<) it outputs something
- in this case "something" is an html formatted page

**Comment by 552020** [comment]
So this doesn't refer to the opened PR, right?

**Comment by lmangall** [comment]
It does, as I sait I was "Making a PR to conform to our "push and PR often policy" but now it makes more sense maybe to open a PR for this branch : `lmangall/web-24-cgi-to-the-browser` …

**Comment by 552020** [comment]
So I'll wait for it. I mean in the screenshot you posted in Slack you had already some code, which was printing something in the browser from the CGI. So this could have been good enough no?

In the PR also daniils's file were added to the review.

**Comment by lmangall** [comment]
Yes you are right it is good enough and better to merge 24 into main. I will see now if I can do some improvements/cleanups and open the PR, hopefully not too many conflicts to solve now that your branch got merged into main.
