### ISSUE TITLE
Write a test for non blocking behaviour while reading

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#181]
Let 100 clients send a GET request, 50 of them (every second one) will send them in two branches with two send, with a delay between both of some seconds. We need a way to identify the clients and check that the first 50 which the server responded to are the ones which sent the request with one send.

**Comment by dantol29** [comment]
I think we tested it with file upload yesterday, no? @lmangall

**Comment by lmangall** [comment]
Yes but this issue is about writing tests, I think my test cover this however

**Comment by dantol29** [comment]
@lmangall Is it in the main and working?

**Comment by dantol29** [comment]
We can easily see it in the browser or with siege

**Comment by 552020** [comment]
Why not to write a small automated test? It is easier to show no?
