### ISSUE TITLE
Decide where to put the path_to_interpreter variable (Server, Router, Connection, CGI)

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#189]
We need to decide where to have this variable, i.e. how to set it when the server is initialized. @lmangall 

@slombard said in [WEB-161](https://linear.app/web-serv/issue/WEB-161/add-a-path-to-interpreter-value-in-the-config-file#comment-618c678b):

> Like Pilate I'll wash my hands on this. Just let me (us) know what you want and where! :-)<br><br>I'll move it as todo and assign it to @dtolmaco as responsible for the config file and add an extra issue for the variable you will need on the Server object. But probably this variable shoule be on the Router object or on the CGIHandler object right? This is also another 'issue' we should think about, if actually the Router object can live 'inside' the Server, i.e. it will not change for each connection. If this is the case when we start the Server it will have a Router object with some variable like the one about how the CGI has to be called.

**Comment by lmangall** [comment]
@dtolmaco there are more information in [this issue](https://linear.app/web-serv/issue/WEB-161/add-a-path-to-interpreter-value-in-the-config-file#comment-618c678b), this "variable" is a triggering meta-variable in the CGI, now in the form of a commented out line in the MetaVariables object:

If we want to go the simple way we set it as a macro

<br>`// env.setVar("X_INTERPRETER_PATH", "/home/lmangall/.brew/bin/python3"); // school computer...`
