### ISSUE TITLE
Write a test to check if we do multiple reads without passing through poll

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#207]
We should never read (or write) a socket multiple times without passing through poll. Check the case in which a request is bigger than the buffer of read and the buffer are smaller. In this scenario: after we read the whole headers with the first read and part of the body, we should not read directly the socket again but we should exit from handleConnection, go back to poll and then finish to read the body in a second read after poll.

**Comment by dantol29** [comment]
I think this is done in Python tests. @slombard What do you think?

**Comment by 552020** [comment]
I don't even know how you can test this. In any case is not something that it can be checked from outside the program I would say. It should be an 'internal' test in the program itself, something like a flag set to 0 when we enter handleConnection and set to ++ after the read, and then get a warning if this value get bigger than 1. <br><br>The python tests test if the webserver works if the request is bigger than the buffer size of read but it doesn't tell us if we read multiple times without going through poll. <br><br>What do you think?

**Comment by dantol29** [comment]
But we can see in the terminal that we go through the poll after each read. We tested this behavior 2 weeks ago and web server is reading only once. The question is do need to write this 'internal' tester? Is it so necessary?
