### ISSUE TITLE
Write test for incomplete headers `GET / HTTP/1.1\r\nHost: www.example.com\r\n\r`

### ISSUE THREAD

**Issue by dantol29** [dantol29/webserver#208]
Currently poll time outs

**Comment by dantol29** [comment]
@552020 Is this fixed?

**Comment by 552020** [comment]
I guess this is not fixed yet. We need also a timeout for Connection in general. We have already a linear issue for that, and I'll tackle it when we are done with the non blocking CGI. This will also mean, that if we have open Connections we will have a timeout on poll.
