### ISSUE TITLE
decide between poll, epoll or select

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#21]
We need to decide which of these functions (poll, epoll, select) to use to handle non blocking I/O operations on sockets. What do you think? @lmangall @dtolmaco 

Here are the pros and cons of using each of them: [https://chat.openai.com/share/90503ef7-4182-41ca-824d-de31a5d6d4b6](https://chat.openai.com/share/90503ef7-4182-41ca-824d-de31a5d6d4b6)

I did a small research on the repos of our mates at school:

* luca/graham/mvomiero [https://github.com/sidechained/webServ](https://github.com/sidechained/webServ): use neither select, nor poll, not epoll b ut FD_ZERO, FD_ISSET, FD_ZERO, FD_SET, FD_CLR which are basically part of the select API.
* tsveto/ramesh [https://github.com/VulpesDev/WebServer](https://github.com/VulpesDev/WebServer): epoll
* lwidmer/pierre/fbecht poll but also select, in two occasions
* jisset/cbadura/htam: poll
* maria/sunny/feras [https://github.com/mariiamakura/webserv](https://github.com/mariiamakura/webserv): poll
* DL: darren/luca [git@github.com](mailto:git@github.com):darrenkuro/42_webserv.git: poll with some FD\_\* functions

**Comment by dantol29** [comment]
I researched a bit and found out that select is not as effective as poll. That is why I am for poll
