### ISSUE TITLE
Implement chunked body response for large 'targets'

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#211]
It's not explicitly mentioned in the subject, but if we want the server being non-blocking even when serving big files, there is no way around, I would say, than sending big responses with a chunked body. I tag here also @dtolmaco and assign this to @lmangall since it's part of the request handler. We should decide if to implement this or not. 

@slombard said in [WEB-154](https://linear.app/web-serv/issue/WEB-154/implement-a-mvp-tester-for-non-blocking-multiplexer#comment-d83fe908):

> Ok. So I started to think about it. A GET request serving a big file (it could be also an HTML page with a big image), will block the server. But there is no other way than to let it not to block than sending a response with a chunked body, and send it with multiple reads. It means that the response handler before sending the respose it should check the size of the file, or if it is an html page with images check the size of the files 'linked' (src=) in the html and if the response is bigger than a certain size then send it with a chunked body.

**Comment by dantol29** [comment]
Right know we send it back in multiple sends. I think it is fine. What do you think? @552020 @lmangall

**Comment by 552020** [comment]
Yes, it's fine. We don't create content that needs a chunked-body response, cause we don't send back streaming or stuff like that. This can be closed. Sending it back in multiple sends with a normal content-length response is fine.
