### ISSUE TITLE
Implement download location for uploaded file in the configuration

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#215]
From the subject:

> \- *Make the route able to accept uploaded files and configure where they should be saved.*

I'm not sure if this has been already implemented in the configuration. @dtolmaco Is it?

**Comment by dantol29** [comment]
This is not mandatory. By default it is downloaded in the root of the host

**Comment by 552020** [comment]
What do you mean it's not mandatory? It is part of the subject! Or am I reading it wrong?

- Make the route able to accept uploaded files and configure where they should be saved.

**Comment by dantol29** [comment]
Hmm, then I have add a new directive `upload_location`

**Comment by dantol29** [comment]
Done here https://github.com/dantol29/webserver/pull/367
