### ISSUE TITLE
Decide about Adoption of CI/CD Tools: Jenkins vs GitHub Actions

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#225]
Continuous Integration and Continuous Deployment (CI/CD) tools are essential for modern software development practices. These tools automate the testing and deployment of code changes, ensuring that new code integrates into the existing codebase without breaking it.<br><br>**Comparison of GitHub Actions and Jenkins**:

1. **GitHub Actions**:
   * **Integration**: Seamlessly integrated with GitHub, providing a straightforward setup for projects hosted on GitHub.
   * **Configuration**: Uses YAML files for workflow definitions, stored within the project repository.
   * **Infrastructure**: Hosted service with a set number of free minutes; additional minutes are paid. Provides a range of virtual environments and containers for testing.
   * **Ease of Use**: Designed with a modern user interface, making workflow creation and monitoring more accessible.
   * **Community and Support**: Strong community support due to its integration with GitHub and growing popularity.
2. **Jenkins**:
   * **Integration**: Can be used with various version control systems but requires more setup and integration work compared to GitHub Actions.
   * **Configuration**: Uses Groovy or traditional job configurations, which can be complex and less intuitive compared to YAML.
   * **Infrastructure**: Self-hosted or cloud-hosted; requires setting up and maintaining servers.
   * **Ease of Use**: The interface is less modern, and the learning curve can be steeper for new users. However, it offers extensive plugins that provide great flexibility and customization.
   * **Community and Support**: Well-established tool with a large community and a vast array of plugins, providing strong support for many different workflows.

## Trivia

* Daniil was confronted with Jenkins during his last job interview
* Fireship seems to swear on GitHub Actions:
  *  [https://www.youtube.com/watch?v=scEDHsr3APg&ab_channel=Fireship](https://www.youtube.com/watch?v=scEDHsr3APg&ab_channel=Fireship)
  * [https://www.youtube.com/watch?v=eB0nUzAI7M8&ab_channel=Fireship](https://www.youtube.com/watch?v=eB0nUzAI7M8&ab_channel=Fireship)
  * [https://www.youtube.com/watch?v=yfBtjLxn_6k&t=244s&ab_channel=BeyondFireship](https://www.youtube.com/watch?v=yfBtjLxn_6k&t=244s&ab_channel=BeyondFireship)

Me personally I'm open to both of them (maybe leaning more to GitHub Actions), but I would leave the choice to the proponent, Daniil. <br><br>Tag: @dtolmaco, @lmangall

**Comment by dantol29** [comment]
I would go with Jenkins, but there is one thing that stops me - hosting. To run Jenkins, we have to host it somewhere. It adds another level of complexity. Jenkins is more advanced and has lots of features, but our project is quite small and gonna use only the basic functionalities of Jenkins. That is why I would use the Github Actions, compact, and user-friendly version of Jenkins.
