### ISSUE TITLE
Write a test for body size bigger or shorter than Content Length

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#253]
From the eval sheet:

* Limit the client body (use: curl -X POST -H "Content-Type: plain/text" --data "BODY IS HERE write something shorter or longer than body limit").

Yes, there is a limit on the size of the body of an HTTP request in NGINX, and it is defined by the `client_max_body_size` directive. This directive determines the maximum allowed size of the client request body and is configured within the NGINX configuration settings.

By default, `client_max_body_size` is set to 1 megabyte (1M). This means that if the body of a request is larger than this limit, NGINX will reject the request with the error "413 Request Entity Too Large". This setting is crucial for preventing denial-of-service (DoS) attacks that might occur by attempting to upload very large files to the server.

You can adjust this setting in the NGINX configuration file (`nginx.conf`) typically located in `/etc/nginx/nginx.conf` or within the server block or HTTP block configurations, depending on your specific setup. For example, to set a larger limit, like 100 megabytes, you would add or modify the following line:

```nginx
client_max_body_size 100M;
```

This setting can be applied globally, or specifically for different server blocks or locations, allowing for flexible configuration depending on the requirements of different applications hosted on the server.

**Comment by dantol29** [comment]
This is done

**Comment by 552020** [comment]
You can close this, the case with the body shorter than Content-Length will not work properly, cause the Connection should time out, but we have it another issue about it.
