### ISSUE TITLE
Decide about reducing the required reviews for merging PRs into main branch

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#261]
I propose to reduce the required reviews to merge PRs into main **from 2 to 1**. As a matter of fact, it is never the case that both reviewers are taking the time to review the PRs, and having another reviewer that should review. The second and more consistent argument is that  @dtolmaco and @lmangall (which are similar views on software development practices, often in contrast with @slombard) could accept each other requests and this could speed up the development of the project

**Comment by dantol29** [comment]
Looks like we can't agree on this. Let's just close it

**Comment by 552020** [comment]
I would still be in favour of the 1 review, but it doesn't really matter. It can be closed.
