### ISSUE TITLE
Avoid garbage values being copied in constructors

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#269]
and copy assignment operator

**Comment by dantol29** [comment]
@552020 Is this done?

**Comment by 552020** [comment]
We need just to try to initialise explicitly always all variables. But to check now if all properties are initialised in the constructor and copy constructor is a lot of work. We can close it or backlog it and just keep in mind that this could cause issue, like the one we had with _hasFinishedRead or something like that.
