### ISSUE TITLE
Note WNOHANG for CGI

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#27]
I spotted this thread in Slack. I guess the WNOHANG flag on waitpid will solve Florian's milestone about the CGI process taking longer than 30 seconds (i.e. taking very long). 

[https://42born2code.slack.com/archives/CN9RHKQHW/p1711440060124479](https://42born2code.slack.com/archives/CN9RHKQHW/p1711440060124479)

A way to solve possible zombie processes is also shown there.

**Comment by lmangall** [comment]
Thank you, just went over it quickly, but I'll need to come back and look at it with more focus.
