### ISSUE TITLE
Gitignore folder in which python test is writing the files

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#271]
The python test for file upload (or whatever test is creating the files) should write them in a directory which is gitignored (otherwise we need to remove manually to switch a branch) or they could get committed.

**Comment by dantol29** [comment]
They are written to the root of the host. I think this is correct.

**Comment by 552020** [comment]
This is not a big issue, just an aesthetic one, it would be cleaner to have them in an ad-hoc folder that doesn't get committed. Super low priority, almost Backlog.
