### ISSUE TITLE
Implement first virtual server as default server for some ip:host

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#291]
We can solve this, witout adding any new variable or stuff just taking the first ServerBlock for a certain ip:host combination if the server_name doesn't match with any Host property from the request. 

@slombard said in [WEB-181](https://linear.app/web-serv/issue/WEB-181/understand-requirement-the-first-server-for-a-hostport-will-be-the#comment-03038e35):

> We discussed yesterday about it, but I would like to make sure that all three understand and agree on what is meant here: @dtolmaco @lmangall. This is important above all for the Router. <br><br>The **connection object** knows the IP:port combination from which the request originated. This is the IP:port of the server socket that accepted the request and generated the client socket. The Connection has this value saved (to be implemented). \[It's not possible that we don't listen to requests to that IP:port combination because the server socket is created based on the 'listen' property of the server blocks in the configuration file.\]<br><br>After the **request** is parsed, we will know for which "Host" (hosted website) the request is. The "Host" header should match the server_name (one of them) of one of our ServerBlocks objects within the Configuration object. \[If multiple server blocks has the same server_name, this should be an error I would say, but there is still the 'complicated' case in which different part of the same websites are served by different virtual host. I'm not sure if we should care about it.\]<br><br>We need now to find out which ServerBlock to load into the Router. We check the "Host" property against the server_name property of the ServerBlock listening to the precise address the Connection indicates the request came from (not against all of them). If we don't find any match, we load the default one, which will be the first one. We don't even need to set a 'default' property on ServerBlock to signalise that that ServerBlock is the default one for that ip:host combination if we save them in the vector of ServerBlock the same way they are declared in the config file.

**Comment by dantol29** [comment]
@552020 if server_name is not found, we just take the first server block?

**Comment by dantol29** [comment]
@552020 if server_name is not found, we just take the first server block?

**Comment by 552020** [comment]
For the address:ip the request is coming from yes. In NGNIX it is the catch-it-all initial server block with server_name "_"

**Comment by dantol29** [comment]
Done here https://github.com/dantol29/webserver/pull/367
