### ISSUE TITLE
Evaluate exit(s)

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#30]
In our code we have already some exit(s), the server should always run and never stop. Dive into the topic and think about how to handle these cases, cause exit should almost never be an option. I guess we should rather throw an error, catch the error, report the error but not shut down the program, cause this would be all the websites we are serving would be down!

@dtolmaco @lmangall

* To exit on the creation of the server socket is reasonable, because the server is not running yet and usually indicating a severe problem with the OS or a misconfiguration of the system's network stack.
* To exit on binding (of the server socket) could be avoided if the server should listen on multiple ports
* To exit on listen is reasonable, but again if the server is already listening on other port we coud avoid this. 

*Retry strategy*

```


int max_retries = 5; // Maximum number of retries
int retry_delay = 1; // Initial delay in seconds, could be increased on each retry

for (int attempt = 0; attempt < max_retries; ++attempt) {
    if (bind(_serverFD, (struct sockaddr *)&_serverAddr, sizeof(_serverAddr)) < 0) {
        perror("Warning: Bind failed, retrying");
        sleep(retry_delay); // Wait before retrying
        // Optionally increase retry_delay here for exponential backoff
    } else {
        // Bind succeeded
        break;
    }
}

if (attempt == max_retries) {
    perror("Critical: Failed to bind after multiple attempts");
    exit(EXIT_FAILURE);
}
```

R

**Comment by hazyq0** [comment]
https://linear.app/web-serv/issue/WEB-33/solve-exits-in-main

**Comment by dantol29** [comment]
HTTPRequest Class has a private attribute \_statusCode that you can use to check if the request is valid or not.
