### ISSUE TITLE
Decide about Adopt Conventional Commits

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#301]
This would be the next step on the way of the professionalisation of the team: [https://www.conventionalcommits.org/en/v1.0.0/](https://www.conventionalcommits.org/en/v1.0.0/)<br><br>We used it at work. <br><br>To the question: What is the best standard for commits messages?<br><br>The model answers:<br><br>Writing effective commit messages is crucial for maintaining a clear and accessible project history. While there is no single "best" standard universally agreed upon, a widely respected approach is the one popularized by the Angular team, often referred to as Conventional Commits. This standard helps automate the versioning and changelog generation processes and maintains readability and consistency in commit logs. Here are some key guidelines from this approach:

1. **Structured Format**: Each commit message should have a clear structure that includes a type, a scope (optional), and a subject:

   ```
   <type>(<scope>): <subject>
   ```
2. **Types**: Common types include:
   * `feat` (new feature)
   * `fix` (bug fix)
   * `docs` (documentation changes)
   * `style` (formatting, missing semicolons, etc.)
   * `refactor` (code change that neither fixes a bug nor adds a feature)
   * `test` (adding missing tests)
   * `chore` (maintenance tasks, e.g., updating grunt tasks etc.)
3. **Scope**: The scope can specify the place of the commit change (e.g., module name, file name).
4. **Subject**: The subject contains a succinct description of the change:
   * Use the imperative mood ("add", not "adds" or "added").
   * Do not capitalize the first letter.
   * No dot (.) at the end.
5. **Body and Footer** (optional but recommended for more complex changes):
   * The body should include a detailed explanation of what changed and why, not how.
   * The footer can contain information about breaking changes and is also used to reference issue tracker IDs.
6. **Examples**:
   * Simple commit: `fix(login): correct minor typos in code`
   * Complex commit:

     ```
     feat(blog): add comment section
     
     Users will now be able to post comments on blog posts.
     
     BREAKING CHANGE: Database schema updated. Run migrations before deploying.
     Resolves #123
     ```

These guidelines help keep the project's commit history informative and navigable, especially useful in collaborative environments where multiple developers need to understand each other’s changes quickly and clearly. Other models and modifications exist, such as using emojis or more specific types, but the Conventional Commits standard is a good starting point for most projects.<br><br>What do you think? @dtolmaco @lmangall

**Comment by lmangall** [comment]
It's a sign:

<img src="https://uploads.linear.app/3a13e0cf-cf78-41bb-abe3-8d0765670e8b/be6ef783-ff60-4889-86ce-a24a4c1b81cf/92f98335-9294-480a-ab21-1157bd4d07f5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNhMTNlMGNmLWNmNzgtNDFiYi1hYmUzLThkMDc2NTY3MGU4Yi9iZTZlZjc4My1mZjYwLTQ4ODktODZjZS1hMjRhNGMxYjgxY2YvOTJmOTgzMzUtOTI5NC00ODBhLWFiMjEtMTE1N2JkNGQwN2Y1IiwiaWF0IjoxNzE1MTI0MzQ5LCJleHAiOjMzMjg1Njg0MzQ5fQ.ZzSVAjEt2hRW1c1xXNTgej5QekLVM88TzOMZn_Xl-cs " alt="image.png" width="1264" height="192" />
