### ISSUE TITLE
Implement listen struct in the config file

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#323]

**Comment by dantol29** [comment]
@slombard What about `std::vector<std::pair<std::string port, std::string address> >`

@slombard

**Comment by 552020** [comment]
It is also good! 
1.  One of the vaue needs to be an int. 
2. The struct has maybe the advantage that is extensible. We could want to say if the address is ANY, but for this case string is suitable. So maybe using pair instead of string is a good solution.
