### ISSUE TITLE
Decide about having a src/ directory or not

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#63]
I'm for it but I will gladly abide by the will of the majority. @dtolmaco

**Comment by dantol29** [comment]
I always create src and includes. I don't see any cons…

**Comment by 552020** [comment]
Just a question @dtolmaco: did you answer to this in Linear or in GitHub? Cause I didn't get notified about the answer in Linear (but in GitHub), which is strange since I'm a 'subscriber' of this issue …

**Comment by dantol29** [comment]
@slombard In Linear
