### ISSUE TITLE
Decide about Orthodox Canonical Form

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#65]
Should we stick as much as possible with the Orthodox Canonical Form, or not? I guess I'm for the OCF but but I will gladly abide by the will of the majority. @dtolmaco 

And should we use constructors as much as possible to create and fill the classes?

**Comment by dantol29** [comment]
I am not the biggest fan of it, because I am lazy and sometimes it is completely unnecessary, but I can write it, not a big deal after all…

I try to use constructors as much as possible. The most straightforward way for me

**Comment by 552020** [comment]
Ok. Let's see what leo says.

**Comment by lmangall** [comment]
I am also for both as this seems to be good practice
